const data = {
  "market-in-seville": {
    audioUrl: "https://res.cloudinary.com/dkhvsbyv6/video/upload/v1773040899/story_output_prerit_srz6bv.mp3",
    
  "transcript": [
    { "speaker": "Person1", "text": "Buenos días." },
    { "speaker": "Person2", "text": "¡Buenos días! ¿Qué día es hoy?" },
    { "speaker": "Person1", "text": "¿Qué día es hoy?" },
    { "speaker": "Person2", "text": "Hoy es viernes, el quince de marzo." },
    { "speaker": "Person1", "text": "¡Qué bonitas naranjas! ¿Cuántos euros cuestan estas?" },
    { "speaker": "Person2", "text": "Esas son cinco euros. ¿Quieres comprar cuántos kilos?" },
    { "speaker": "Person1", "text": "Mmm, quiero dos kilos. ¿Tienes la fruta hasta las veinte?" },
    { "speaker": "Person2", "text": "Sí, hasta las veinte. ¿Y tú, qué vendes?" },
    { "speaker": "Person1", "text": "Me gustan los colores. ¿Qué color es ese melón?" },
    { "speaker": "Person2", "text": "El melón es verde. ¿Y tu color favorito?" },
    { "speaker": "Person1", "text": "Mi color favorito es morado. ¡Este pato es muy gordo!" },
    { "speaker": "Person2", "text": "Jaja, ¡no es un pato, es una calabaza! ¿Es para ti o para alguien más?" },
    { "speaker": "Person1", "text": "¿Cuándo es tu próxima cita?" },
    { "speaker": "Person2", "text": "Mi próxima cita es mañana. ¿Y la tuya?" },
    { "speaker": "Person1", "text": "No tengo una cita. ¿Venden aquí jabón?" },
    { "speaker": "Person2", "text": "No, aquí no. Pero sí vendemos jamón." },
    { "speaker": "Person2", "text": "Yo estoy aquí hasta las veinte. Mi cita es a las cinco. ¿Y tú, qué haces?" },
    { "speaker": "Person1", "text": "Yo estoy leyendo un libro. ¡Qué sorpresa! Mi gemelo es lector." },
    { "speaker": "Person2", "text": "Interesante. Yo soy vendedor. Gracias por preguntar." },
    { "speaker": "Person1", "text": "El perro está hambriento, ¿verdad?" },
    { "speaker": "Person1", "text": "Quiero comprar esto. ¿En qué año estamos?" },
    { "speaker": "Person2", "text": "Estamos en dos mil veinticuatro. ¿Te gustan los meses de abril o mayo?" },
    { "speaker": "Person1", "text": "Me gustan más julio. ¿Tú hablas español todos los días?" },
    { "speaker": "Person2", "text": "Sí, yo hablo español todos los días. Ustedes hablan muy bien." },
    { "speaker": "Person1", "text": "¡Muchas gracias! ¡Somos amigos ahora!" },
    { "speaker": "Person2", "text": "¡Claro que sí! ¡Buen día! Quizás adivina el país. ¡Ecuador!" },
    { "speaker": "Person1", "text": "¡Ecuador! ¡Me encanta! ¡Adiós!" },
    { "speaker": "Person2", "text": "¡Adiós! ¡Vuelve pronto!" }
  ],
  "translated": [
    { "speaker": "Person1", "text": "Good morning." },
    { "speaker": "Person2", "text": "Good morning! What day is it today?" },
    { "speaker": "Person1", "text": "What day is it today?" },
    { "speaker": "Person2", "text": "Today is Friday, March fifteenth." },
    { "speaker": "Person1", "text": "What beautiful oranges! How many euros do these cost?" },
    { "speaker": "Person2", "text": "Those are five euros. How many kilos do you want to buy?" },
    { "speaker": "Person1", "text": "Hmm, I want two kilos. Do you have fruit until eight?" },
    { "speaker": "Person2", "text": "Yes, until eight. And you, what do you sell?" },
    { "speaker": "Person1", "text": "I like the colors. What color is that melon?" },
    { "speaker": "Person2", "text": "The melon is green. And your favorite color?" },
    { "speaker": "Person1", "text": "My favorite color is purple. This duck is very fat!" },
    { "speaker": "Person2", "text": "Haha, it’s not a duck, it’s a pumpkin! Is it for you or for someone else?" },
    { "speaker": "Person1", "text": "When is your next appointment?" },
    { "speaker": "Person2", "text": "My next appointment is tomorrow. And yours?" },
    { "speaker": "Person1", "text": "I don’t have an appointment. Do they sell soap here?" },
    { "speaker": "Person2", "text": "No, not here. But we do sell ham." },
    { "speaker": "Person2", "text": "I am here until eight. My appointment is at five. And you, what are you doing?" },
    { "speaker": "Person1", "text": "I am reading a book. What a surprise! My twin is a reader." },
    { "speaker": "Person2", "text": "Interesting. I am a vendor. Thanks for asking." },
    { "speaker": "Person1", "text": "The dog is hungry, right?" },
    { "speaker": "Person1", "text": "I want to buy this. What year are we in?" },
    { "speaker": "Person2", "text": "We are in 2024. Do you like the months April or May?" },
    { "speaker": "Person1", "text": "I like July more. Do you speak Spanish every day?" },
    { "speaker": "Person2", "text": "Yes, I speak Spanish every day. You speak very well." },
    { "speaker": "Person1", "text": "Thank you very much! We are friends now!" },
    { "speaker": "Person2", "text": "Of course! Have a good day! Maybe guess the country. Ecuador!" },
    { "speaker": "Person1", "text": "Ecuador! I love it! Goodbye!" },
    { "speaker": "Person2", "text": "Goodbye! Come back soon!" }
  ]
  },


  "tour-in-seville": {
    audioUrl: "https://res.cloudinary.com/dkhvsbyv6/video/upload/v1773055221/story_output_rakesh_ppk8bn.mp3",
    transcript: [
  { speaker: "Person1", text: "Ay, qué día tan largo. Estoy muy cansada." },
  { speaker: "Person2", text: "¡Hola! Siéntate un momento. ¿Necesitas algo?" },
  { speaker: "Person1", text: "Sí, por favor. Me siento un poco perdida y cansada." },
  { speaker: "Person2", text: "No te preocupes. Es normal sentirse así en una ciudad nueva." },
  { speaker: "Person1", text: "Gracias. Necesito recomendaciones. ¿Qué recomiendas tú para hacer en Sevilla?" },
  { speaker: "Person2", text: "¿Qué haces normalmente cuando viajas?" },
  { speaker: "Person1", text: "Normalmente, me gusta caminar y ver los monumentos." },
  { speaker: "Person2", text: "Entiendo. Aquí, en Sevilla, hay mucho que ver." },
  { speaker: "Person1", text: "Cuando estoy de vacaciones, yo no trabajo, ¡claro!" },
  { speaker: "Person2", text: "¡Claro! Y para mí, 'yo hablo' español, pero tú hablas inglés, ¿verdad?" },
  { speaker: "Person1", text: "Sí, un poco de español. Pero mi inglés es mejor." },
  { speaker: "Person2", text: "Perfecto. Entonces, te sugiero el barrio de Triana." },
  { speaker: "Person2", text: "¿Quieres ir a Triana mañana por la mañana?" },
  { speaker: "Person1", text: "¡Sí! Yo voy a Triana mañana." },
  { speaker: "Person2", text: "¿Y tú? ¿Vas a estar aquí todo el día?" },
  { speaker: "Person1", text: "No. Después de Triana, no sé qué más voy a hacer." },
  { speaker: "Person2", text: "Triana es muy bonito. Puedes ver el río y los talleres de cerámica." },
  { speaker: "Person1", text: "¡Suena perfecto! Voy a disfrutarlo mucho." },
  { speaker: "Person2", text: "Entonces, ¿vas a ir temprano?" },
  { speaker: "Person1", text: "Sí, voy a salir pronto de mi alojamiento." },
  { speaker: "Person2", text: "Buena idea. Yo abro la cafetería a las siete, así que puedes pasar si quieres un café antes." },
  { speaker: "Person1", text: "¡Genial! Quizás yo hablo contigo mañana por la mañana." },
  { speaker: "Person2", text: "¡Me encantaría! Que tengas un buen día." },
  { speaker: "Person1", text: "Igualmente. ¡Gracias por todo!" }
],

translated: [
  { speaker: "Person1", text: "Oh, what a long day. I am very tired." },
  { speaker: "Person2", text: "Hello! Sit down for a moment. Do you need something?" },
  { speaker: "Person1", text: "Yes, please. I feel a little lost and tired." },
  { speaker: "Person2", text: "Don't worry. It's normal to feel like that in a new city." },
  { speaker: "Person1", text: "Thanks. I need recommendations. What do you recommend doing in Seville?" },
  { speaker: "Person2", text: "What do you usually do when you travel?" },
  { speaker: "Person1", text: "Normally, I like to walk and see monuments." },
  { speaker: "Person2", text: "I understand. Here in Seville, there is a lot to see." },
  { speaker: "Person1", text: "When I'm on vacation, I don't work, of course!" },
  { speaker: "Person2", text: "Of course! And for me, I speak Spanish, but you speak English, right?" },
  { speaker: "Person1", text: "Yes, a little Spanish. But my English is better." },
  { speaker: "Person2", text: "Perfect. Then I suggest the neighborhood of Triana." },
  { speaker: "Person2", text: "Do you want to go to Triana tomorrow morning?" },
  { speaker: "Person1", text: "Yes! I am going to Triana tomorrow." },
  { speaker: "Person2", text: "And you? Are you going to be here all day?" },
  { speaker: "Person1", text: "No. After Triana, I don't know what else I will do." },
  { speaker: "Person2", text: "Triana is very beautiful. You can see the river and the ceramic workshops." },
  { speaker: "Person1", text: "That sounds perfect! I will enjoy it a lot." },
  { speaker: "Person2", text: "So, are you going to go early?" },
  { speaker: "Person1", text: "Yes, I am going to leave my accommodation early." },
  { speaker: "Person2", text: "Good idea. I open the café at seven, so you can stop by if you want a coffee before." },
  { speaker: "Person1", text: "Great! Maybe I will talk with you tomorrow morning." },
  { speaker: "Person2", text: "I would love that! Have a good day." },
  { speaker: "Person1", text: "Likewise. Thanks for everything!" }
],
  },

  "Intro": {
    audioUrl: "https://res.cloudinary.com/dkhvsbyv6/video/upload/v1773122234/rohan_but6ie.mp3",
    
  "transcript": [
    { "speaker": "Person1", "text": "¡Hola! ¿Cómo estás?" },
    { "speaker": "Person2", "text": "Estoy bien, pero estoy cansado." },
    { "speaker": "Person1", "text": "¿Cansado? ¿Por qué?" },
    { "speaker": "Person2", "text": "Las máquinas del gimnasio esta mañana fueron intensas." },
    { "speaker": "Person1", "text": "Sí, esas máquinas son duras." },
    { "speaker": "Person2", "text": "Pero quiero nuevos logros con mi entrenamiento." },
    { "speaker": "Person2", "text": "Mantenerse activo es fundamental para mí." },
    { "speaker": "Person1", "text": "Eso es un verdadero desafío." },
    { "speaker": "Person1", "text": "Mi primo empezó a entrenar también." },
    { "speaker": "Person1", "text": "Y mi prima prefiere correr en los bosques fuera de la ciudad." },
    { "speaker": "Person2", "text": "¿Los bosques? Me encanta eso de este país." },
    { "speaker": "Person2", "text": "En Tennessee tenemos bosques también, pero estos se sienten diferentes." },
    { "speaker": "Person1", "text": "Eso me recuerda algo. ¿Lo que más te gusta de Colombia?" },
    { "speaker": "Person2", "text": "Lo que más me gusta de Colombia es la gente." },
    { "speaker": "Person1", "text": "¿Tu familia sigue en Tennessee?" },
    { "speaker": "Person2", "text": "Sí. Mi abuela está muy activa allí." },
    { "speaker": "Person1", "text": "Mi abuela también está muy activa, especialmente en Navidad." },
    { "speaker": "Person2", "text": "¿Celebran diferente aquí?" },
    { "speaker": "Person1", "text": "Sí, tenemos algo llamado novena." },
    { "speaker": "Person1", "text": "Las familias se reúnen por nueve noches, comparten regalos y cantan villancicos." },
    { "speaker": "Person2", "text": "Suena increíble, pero no tengo familia aquí para Navidad." },
    { "speaker": "Person1", "text": "Entonces ven con nosotros. No es un desafío, solo ven." },
    { "speaker": "Person2", "text": "Gracias. Soy muy afortunado de tener una amiga como tú." },
    { "speaker": "Person2", "text": "Lo que más me gusta de este café es el café." },
    { "speaker": "Person1", "text": "¡El café colombiano es el mejor!" }
  ],
  "translated": [
    { "speaker": "Person1", "text": "Hi! How are you?" },
    { "speaker": "Person2", "text": "I am well, but I am tired." },
    { "speaker": "Person1", "text": "Tired? Why?" },
    { "speaker": "Person2", "text": "The gym machines this morning were intense." },
    { "speaker": "Person1", "text": "Yes, those machines are tough." },
    { "speaker": "Person2", "text": "But I want new achievements with my training." },
    { "speaker": "Person2", "text": "Staying active is fundamental for me." },
    { "speaker": "Person1", "text": "That is a real challenge." },
    { "speaker": "Person1", "text": "My male cousin started training too." },
    { "speaker": "Person1", "text": "And my female cousin prefers running in the forests outside the city." },
    { "speaker": "Person2", "text": "The forests? I love that about this country." },
    { "speaker": "Person2", "text": "In Tennessee we have forests too, but these feel different." },
    { "speaker": "Person1", "text": "That reminds me of something. What do you like most about Colombia?" },
    { "speaker": "Person2", "text": "What I like most about Colombia is the people." },
    { "speaker": "Person1", "text": "Your family is still in Tennessee?" },
    { "speaker": "Person2", "text": "Yes. My grandmother is very active there." },
    { "speaker": "Person1", "text": "My grandmother is also very active, especially at Christmas." },
    { "speaker": "Person2", "text": "Do you celebrate differently here?" },
    { "speaker": "Person1", "text": "Yes, we have something called a novena." },
    { "speaker": "Person1", "text": "Families gather for nine nights, share gifts, and sing Christmas carols." },
    { "speaker": "Person2", "text": "That sounds amazing, but I don't have family here for Christmas." },
    { "speaker": "Person1", "text": "Then come with us. It's not a challenge, just come." },
    { "speaker": "Person2", "text": "Thank you. I am very lucky to have a friend like you." },
    { "speaker": "Person2", "text": "What I like most about this café is the coffee." },
    { "speaker": "Person1", "text": "Colombian coffee is the best!" }
  ]

  },
};

export default data;
