const data = {
  "market-in-seville": {
    audioUrl: "https://res.cloudinary.com/dkhvsbyv6/video/upload/v1773040899/story_output_prerit_srz6bv.mp3",
    
  "transcript": [
    { "speaker": "Person1", "text": "Buenos días." },
    { "speaker": "Person2", "text": "¡Buenos días! ¿Qué día es hoy?" },
    { "speaker": "Person1", "text": "¿Qué día es hoy?" },
    { "speaker": "Person2", "text": "Hoy es viernes, el quince de marzo." },
    { "speaker": "Person1", "text": "¡Qué bonitas naranjas! ¿Cuántos euros cuestan estas?" },
    { "speaker": "Person2", "text": "Esas son cinco euros. ¿Quieres comprar cuántos kilos?" },
    { "speaker": "Person1", "text": "Mmm, quiero dos kilos. ¿Tienes la fruta hasta las veinte?" },
    { "speaker": "Person2", "text": "Sí, hasta las veinte. ¿Y tú, qué vendes?" },
    { "speaker": "Person1", "text": "Me gustan los colores. ¿Qué color es ese melón?" },
    { "speaker": "Person2", "text": "El melón es verde. ¿Y tu color favorito?" },
    { "speaker": "Person1", "text": "Mi color favorito es morado. ¡Este pato es muy gordo!" },
    { "speaker": "Person2", "text": "Jaja, ¡no es un pato, es una calabaza! ¿Es para ti o para alguien más?" },
    { "speaker": "Person1", "text": "¿Cuándo es tu próxima cita?" },
    { "speaker": "Person2", "text": "Mi próxima cita es mañana. ¿Y la tuya?" },
    { "speaker": "Person1", "text": "No tengo una cita. ¿Venden aquí jabón?" },
    { "speaker": "Person2", "text": "No, aquí no. Pero sí vendemos jamón." },
    { "speaker": "Person2", "text": "Yo estoy aquí hasta las veinte. Mi cita es a las cinco. ¿Y tú, qué haces?" },
    { "speaker": "Person1", "text": "Yo estoy leyendo un libro. ¡Qué sorpresa! Mi gemelo es lector." },
    { "speaker": "Person2", "text": "Interesante. Yo soy vendedor. Gracias por preguntar." },
    { "speaker": "Person1", "text": "El perro está hambriento, ¿verdad?" },
    { "speaker": "Person1", "text": "Quiero comprar esto. ¿En qué año estamos?" },
    { "speaker": "Person2", "text": "Estamos en dos mil veinticuatro. ¿Te gustan los meses de abril o mayo?" },
    { "speaker": "Person1", "text": "Me gustan más julio. ¿Tú hablas español todos los días?" },
    { "speaker": "Person2", "text": "Sí, yo hablo español todos los días. Ustedes hablan muy bien." },
    { "speaker": "Person1", "text": "¡Muchas gracias! ¡Somos amigos ahora!" },
    { "speaker": "Person2", "text": "¡Claro que sí! ¡Buen día! Quizás adivina el país. ¡Ecuador!" },
    { "speaker": "Person1", "text": "¡Ecuador! ¡Me encanta! ¡Adiós!" },
    { "speaker": "Person2", "text": "¡Adiós! ¡Vuelve pronto!" }
  ],
  "translated": [
    { "speaker": "Person1", "text": "Good morning." },
    { "speaker": "Person2", "text": "Good morning! What day is it today?" },
    { "speaker": "Person1", "text": "What day is it today?" },
    { "speaker": "Person2", "text": "Today is Friday, March fifteenth." },
    { "speaker": "Person1", "text": "What beautiful oranges! How many euros do these cost?" },
    { "speaker": "Person2", "text": "Those are five euros. How many kilos do you want to buy?" },
    { "speaker": "Person1", "text": "Hmm, I want two kilos. Do you have fruit until eight?" },
    { "speaker": "Person2", "text": "Yes, until eight. And you, what do you sell?" },
    { "speaker": "Person1", "text": "I like the colors. What color is that melon?" },
    { "speaker": "Person2", "text": "The melon is green. And your favorite color?" },
    { "speaker": "Person1", "text": "My favorite color is purple. This duck is very fat!" },
    { "speaker": "Person2", "text": "Haha, it’s not a duck, it’s a pumpkin! Is it for you or for someone else?" },
    { "speaker": "Person1", "text": "When is your next appointment?" },
    { "speaker": "Person2", "text": "My next appointment is tomorrow. And yours?" },
    { "speaker": "Person1", "text": "I don’t have an appointment. Do they sell soap here?" },
    { "speaker": "Person2", "text": "No, not here. But we do sell ham." },
    { "speaker": "Person2", "text": "I am here until eight. My appointment is at five. And you, what are you doing?" },
    { "speaker": "Person1", "text": "I am reading a book. What a surprise! My twin is a reader." },
    { "speaker": "Person2", "text": "Interesting. I am a vendor. Thanks for asking." },
    { "speaker": "Person1", "text": "The dog is hungry, right?" },
    { "speaker": "Person1", "text": "I want to buy this. What year are we in?" },
    { "speaker": "Person2", "text": "We are in 2024. Do you like the months April or May?" },
    { "speaker": "Person1", "text": "I like July more. Do you speak Spanish every day?" },
    { "speaker": "Person2", "text": "Yes, I speak Spanish every day. You speak very well." },
    { "speaker": "Person1", "text": "Thank you very much! We are friends now!" },
    { "speaker": "Person2", "text": "Of course! Have a good day! Maybe guess the country. Ecuador!" },
    { "speaker": "Person1", "text": "Ecuador! I love it! Goodbye!" },
    { "speaker": "Person2", "text": "Goodbye! Come back soon!" }
  ]
  },


  "tour-in-seville": {
    audioUrl: "https://res.cloudinary.com/dkhvsbyv6/video/upload/v1773055221/story_output_rakesh_ppk8bn.mp3",
    transcript: [
  { speaker: "Person1", text: "Ay, qué día tan largo. Estoy muy cansada." },
  { speaker: "Person2", text: "¡Hola! Siéntate un momento. ¿Necesitas algo?" },
  { speaker: "Person1", text: "Sí, por favor. Me siento un poco perdida y cansada." },
  { speaker: "Person2", text: "No te preocupes. Es normal sentirse así en una ciudad nueva." },
  { speaker: "Person1", text: "Gracias. Necesito recomendaciones. ¿Qué recomiendas tú para hacer en Sevilla?" },
  { speaker: "Person2", text: "¿Qué haces normalmente cuando viajas?" },
  { speaker: "Person1", text: "Normalmente, me gusta caminar y ver los monumentos." },
  { speaker: "Person2", text: "Entiendo. Aquí, en Sevilla, hay mucho que ver." },
  { speaker: "Person1", text: "Cuando estoy de vacaciones, yo no trabajo, ¡claro!" },
  { speaker: "Person2", text: "¡Claro! Y para mí, 'yo hablo' español, pero tú hablas inglés, ¿verdad?" },
  { speaker: "Person1", text: "Sí, un poco de español. Pero mi inglés es mejor." },
  { speaker: "Person2", text: "Perfecto. Entonces, te sugiero el barrio de Triana." },
  { speaker: "Person2", text: "¿Quieres ir a Triana mañana por la mañana?" },
  { speaker: "Person1", text: "¡Sí! Yo voy a Triana mañana." },
  { speaker: "Person2", text: "¿Y tú? ¿Vas a estar aquí todo el día?" },
  { speaker: "Person1", text: "No. Después de Triana, no sé qué más voy a hacer." },
  { speaker: "Person2", text: "Triana es muy bonito. Puedes ver el río y los talleres de cerámica." },
  { speaker: "Person1", text: "¡Suena perfecto! Voy a disfrutarlo mucho." },
  { speaker: "Person2", text: "Entonces, ¿vas a ir temprano?" },
  { speaker: "Person1", text: "Sí, voy a salir pronto de mi alojamiento." },
  { speaker: "Person2", text: "Buena idea. Yo abro la cafetería a las siete, así que puedes pasar si quieres un café antes." },
  { speaker: "Person1", text: "¡Genial! Quizás yo hablo contigo mañana por la mañana." },
  { speaker: "Person2", text: "¡Me encantaría! Que tengas un buen día." },
  { speaker: "Person1", text: "Igualmente. ¡Gracias por todo!" }
],

translated: [
  { speaker: "Person1", text: "Oh, what a long day. I am very tired." },
  { speaker: "Person2", text: "Hello! Sit down for a moment. Do you need something?" },
  { speaker: "Person1", text: "Yes, please. I feel a little lost and tired." },
  { speaker: "Person2", text: "Don't worry. It's normal to feel like that in a new city." },
  { speaker: "Person1", text: "Thanks. I need recommendations. What do you recommend doing in Seville?" },
  { speaker: "Person2", text: "What do you usually do when you travel?" },
  { speaker: "Person1", text: "Normally, I like to walk and see monuments." },
  { speaker: "Person2", text: "I understand. Here in Seville, there is a lot to see." },
  { speaker: "Person1", text: "When I'm on vacation, I don't work, of course!" },
  { speaker: "Person2", text: "Of course! And for me, I speak Spanish, but you speak English, right?" },
  { speaker: "Person1", text: "Yes, a little Spanish. But my English is better." },
  { speaker: "Person2", text: "Perfect. Then I suggest the neighborhood of Triana." },
  { speaker: "Person2", text: "Do you want to go to Triana tomorrow morning?" },
  { speaker: "Person1", text: "Yes! I am going to Triana tomorrow." },
  { speaker: "Person2", text: "And you? Are you going to be here all day?" },
  { speaker: "Person1", text: "No. After Triana, I don't know what else I will do." },
  { speaker: "Person2", text: "Triana is very beautiful. You can see the river and the ceramic workshops." },
  { speaker: "Person1", text: "That sounds perfect! I will enjoy it a lot." },
  { speaker: "Person2", text: "So, are you going to go early?" },
  { speaker: "Person1", text: "Yes, I am going to leave my accommodation early." },
  { speaker: "Person2", text: "Good idea. I open the café at seven, so you can stop by if you want a coffee before." },
  { speaker: "Person1", text: "Great! Maybe I will talk with you tomorrow morning." },
  { speaker: "Person2", text: "I would love that! Have a good day." },
  { speaker: "Person1", text: "Likewise. Thanks for everything!" }
],
  },

  "Intro": {
    audioUrl: "https://res.cloudinary.com/dkhvsbyv6/video/upload/v1773122234/rohan_but6ie.mp3",
    
    transcript: [
      { speaker: "Narrator", text: "It's a warm December afternoon in Medellín, Colombia. Jake, an American who moved here three months ago, walks into a café where his friend Ana is waiting." },
    
      { speaker: "Person1", text: "¡Hola Jake! ¿Cómo estás?" },
      { speaker: "Person2", text: "Estoy bien, but also estoy cansado." },
      { speaker: "Person1", text: "¿Cansado? ¿Por qué?" },
      { speaker: "Person2", text: "Las máquinas, meaning the machines, at the gym this morning were intense!" },
    
      { speaker: "Narrator", text: "Jake said 'Estoy cansado' using the verb 'estar.' Spanish has two verbs for 'to be': 'ser' and 'estar.' 'Estar' is for temporary states." },
    
      { speaker: "Person1", text: "I know those máquinas, those machines — they're tough!" },
      { speaker: "Person2", text: "Sí, yes, but I want new logros, meaning achievements, with my training." },
      { speaker: "Person2", text: "Staying active es fundamental, meaning is fundamental, for me." },
    
      { speaker: "Person1", text: "New logros, new achievements — that's a real desafío, a real challenge!" },
      { speaker: "Person1", text: "My primo, meaning my male cousin, just started training too." },
      { speaker: "Person1", text: "And my prima, my female cousin, prefers running in los bosques, the forests, outside the city." },
    
      { speaker: "Person2", text: "¿Los bosques? The forests? I love that about this country." },
      { speaker: "Person2", text: "In Tennessee, we have bosques, forests, too, but these feel different." },
    
      { speaker: "Person1", text: "That reminds me — lo que más te gusta de Colombia?" },
      { speaker: "Person1", text: "That reminds me — what do you like most about Colombia?" },
    
      { speaker: "Person2", text: "Lo que más me gusta de Colombia, what I like most about Colombia, es la gente, is the people." },
    
      { speaker: "Person1", text: "¡La gente! The people! That's sweet. Your family is still in Tennessee?" },
    
      { speaker: "Person2", text: "Sí, yes. My abuela, my grandmother, ella está muy activa there." },
      { speaker: "Person2", text: "She is very active there." },
    
      { speaker: "Person1", text: "My abuela, my grandmother, too! Ella está muy activa, she is very active, especially around Christmas." },
    
      { speaker: "Person2", text: "Christmas! Do you celebrate differently here?" },
    
      { speaker: "Person1", text: "Sí, yes! We have something called a novena, meaning a period of nueve, nine, days." },
      { speaker: "Person1", text: "Families gather for nueve, nine, nights, share regalos meaning gifts, and sing villancicos meaning Christmas carols." },
    
      { speaker: "Person2", text: "That sounds amazing. But no tengo, meaning I don't have, family here for Christmas." },
    
      { speaker: "Person1", text: "Then come to ours! No es un desafío, meaning it's not a challenge — just show up!" },
    
      { speaker: "Person2", text: "Gracias, thank you, Ana. Soy, meaning I am, very lucky to have you as a friend." },
    
      { speaker: "Person2", text: "Lo que más me gusta de this café, what I like most about this café, es el café, is the coffee." },
      { speaker: "Person1", text: "¡El café colombiano es the best! Colombian coffee is the best!" },
    
      { speaker: "Narrator", text: "Now let's test what you've learned with five quick questions." },
    
      { speaker: "narrator_question", text: "Question 1: True or False — 'Estar' is used for permanent traits like nationality, and 'ser' is used for temporary feelings." },
      { speaker: "narrator_question", text: "Question 2: True or False — To negate a sentence in Spanish, you place 'no' directly before the verb." },
      { speaker: "narrator_question", text: "Question 3: True or False — A woman would say 'Estoy cansado' to express that she is tired." },
      { speaker: "narrator_question", text: "Question 4: True or False — 'Lo que más te gusta de Colombia' means 'What do you like most about Colombia.'" },
      { speaker: "narrator_question", text: "Question 5: True or False — 'Es fundamental' uses 'estar' because it describes a temporary opinion." }
    ],
    
    translated: [
      { speaker: "Narrator", text: "" },
    
      { speaker: "Person1", text: "Hi Jake! How are you?" },
      { speaker: "Person2", text: "I am well, but also I am tired." },
      { speaker: "Person1", text: "Tired? Why?" },
      { speaker: "Person2", text: "The machines at the gym this morning were intense!" },
    
      { speaker: "Narrator", text: "" },
    
      { speaker: "Person1", text: "" },
      { speaker: "Person2", text: "" },
      { speaker: "Person2", text: "" },
    
      { speaker: "Person1", text: "" },
      { speaker: "Person1", text: "" },
      { speaker: "Person1", text: "" },
    
      { speaker: "Person2", text: "" },
      { speaker: "Person2", text: "" },
    
      { speaker: "Person1", text: "" },
      { speaker: "Person1", text: "That reminds me — what do you like most about Colombia?" },
    
      { speaker: "Person2", text: "" },
    
      { speaker: "Person1", text: "" },
    
      { speaker: "Person2", text: "" },
      { speaker: "Person2", text: "She is very active there." },
    
      { speaker: "Person1", text: "" },
    
      { speaker: "Person2", text: "" },
    
      { speaker: "Person1", text: "" },
      { speaker: "Person1", text: "" },
    
      { speaker: "Person2", text: "" },
    
      { speaker: "Person1", text: "" },
    
      { speaker: "Person2", text: "" },
    
      { speaker: "Person2", text: "" },
      { speaker: "Person1", text: "" },
    
      { speaker: "Narrator", text: "" },
    
      { speaker: "narrator_question", text: "" },
      { speaker: "narrator_question", text: "" },
      { speaker: "narrator_question", text: "" },
      { speaker: "narrator_question", text: "" },
      { speaker: "narrator_question", text: "" }
    ]
    
  },

  "vanessa-lynne": {
    audioUrl: "https://res.cloudinary.com/dkhvsbyv6/video/upload/v1773400202/vanessa_rodriguez_lynne_itr3_jydk6f.mp3",
    transcript: [
    { speaker: "Narrator", text: "Clara, a spirited home chef, begins preparing an elaborate soufflé recipe in her kitchen, much to the immediate, vocal interest of her Golden Retriever, Barkley." },
    { speaker: "Person1", text: "Oh, ¡Joy! (I am) excited for this soufflé! This is a ¡bueno di! (good day) to bake!" },
    { speaker: "Person2", text: "My mood is also ¡bueno! (good), Clara. I ¡tener hang! (am hungry) already, even before cooking starts!" },
    { speaker: "Narrator", text: "Clara uses 'Joy' as 'I am' and 'excited' to express her emotion. Barkley uses 'tener hang' to express 'to have hunger', which is the Spanish way to say 'I am hungry'." },
    { speaker: "Person1", text: "Barkley, you are my ¡amigo! (friend), but please, no licking the counter when I'm ¡friendo! (learning) this recipe." },
    { speaker: "Person2", text: "But my profession as ¡amigo! (friend) includes 'taste-tester' and 'cleaner'! It is my identity." },
    { speaker: "Narrator", text: "Barkley calls Clara his 'amigo', the masculine form of 'friend'. He also uses 'friendo' as 'learning' or 'doing in progress' to describe Clara's activity, and 'identity' for a permanent characteristic." },
    { speaker: "Person1", text: "Oops! Almost a disaster! I nearly added salt instead of sugar. My Feelings are a bit ¡enoadas! (angry) with myself." },
    { speaker: "Person2", text: "No, no, Clara, ¡two estaso! (you are) not making a ¡bueno! (good) choice with that salt! My nose detected it!" },
    { speaker: "Narrator", text: "Clara uses 'enoadas', which means 'angry' (feminine plural) to describe her feelings towards herself. Barkley uses 'two estaso', meaning 'you are' (temporary), to describe Clara's action in progress." },
    { speaker: "Person1", text: "The kitchen is so hot with the oven on! I really ¡tener thirsty! (am thirsty) after all this whisking." },
    { speaker: "Person2", text: "The weather is hot inside! And I ¡tener hang! (am hungry) for the soufflé, not just water. It is my permanent character trait." },
    { speaker: "Narrator", text: "Both characters use 'tener' (to have) with 'hot' and 'thirsty' to express their physical sensations, as is common in Spanish. Barkley also uses 'character' for his inherent trait." },
    { speaker: "Person1", text: "And here it is! A perfectly risen soufflé! ¡Bueno! (Good)!" },
    { speaker: "Person2", text: "Magnificent, Clara! A ¡bueno! (good) soufflé indeed. ¡Lyn grass! (Thanks) for this ¡rel! (relationships)." },
    { speaker: "Person1", text: "¡Nosy weos! (We laugh together) at my baking success, Barkley! This family moment is perfect." },
    { speaker: "Narrator", text: "Barkley expresses 'thanks' with 'Lyn grass' and refers to their 'relationships' as 'rel'. Clara uses 'Nosy weos' to say 'we laugh together' (without a 'to be' verb), emphasizing their shared 'family' bond. The soufflé was delicious, and Barkley, the talking dog, gave it his highest praise." },
    { speaker: "narrator_question", text: "Question 1: True or False — The word 'Australiana' describes a nationality, which typically uses the verb 'ser' in Spanish." },
    { speaker: "Narrator", text: "True. The grammar rules state that 'ser' is used for nationalities." },
    { speaker: "narrator_question", text: "Question 2: True or False — In Spanish, the verb 'ser' is used for temporary situations like location or emotions." },
    { speaker: "Narrator", text: "False. The verb 'ser' is used for permanent characteristics; 'estad' (to be temporary) is used for location, weather, and emotions." },
    { speaker: "narrator_question", text: "Question 3: True or False — The word 'Joy' means 'I am' and is correctly paired with the pronoun 'Yo'." },
    { speaker: "Narrator", text: "True. 'Joy' translates to 'I am', and 'Yo' translates to 'I', following the rule of pronoun-verb concordance." },
    { speaker: "narrator_question", text: "Question 4: True or False — The words 'amigo' and 'amigga' illustrate how nouns and adjectives in Spanish often change their ending to match gender." },
    { speaker: "Narrator", text: "True. 'Amigo' (masculine) and 'amigga' (feminine) demonstrate the gender agreement rule with 'o' and 'a' endings." },
    { speaker: "narrator_question", text: "Question 5: True or False — To express feeling 'hang' (hungry) in Spanish, you would use a form of 'estad' (to be temporary)." },
    { speaker: "Narrator", text: "False. To express 'hang' (hungry), 'thirsty', or feeling 'hot', the verb 'tener' (to have) is used, not a form of 'estad'." }
    ],
    translated: [
    { speaker: "Narrator", text: "" },
    { speaker: "Person1", text: "" },
    { speaker: "Person2", text: "" },
    { speaker: "Narrator", text: "" },
    { speaker: "Person1", text: "" },
    { speaker: "Person2", text: "" },
    { speaker: "Narrator", text: "" },
    { speaker: "Person1", text: "" },
    { speaker: "Person2", text: "" },
    { speaker: "Narrator", text: "" },
    { speaker: "Person1", text: "" },
    { speaker: "Person2", text: "" },
    { speaker: "Narrator", text: "" },
    { speaker: "Person1", text: "" },
    { speaker: "Person2", text: "" },
    { speaker: "Person1", text: "" },
    { speaker: "Narrator", text: "" },
    { speaker: "narrator_question", text: "" },
    { speaker: "Narrator", text: "" },
    { speaker: "narrator_question", text: "" },
    { speaker: "Narrator", text: "" },
    { speaker: "narrator_question", text: "" },
    { speaker: "Narrator", text: "" },
    { speaker: "narrator_question", text: "" },
    { speaker: "Narrator", text: "" },
    { speaker: "narrator_question", text: "" },
    { speaker: "Narrator", text: "" }
    ],
  },

  "camila-alissa": {
    audioUrl: "https://res.cloudinary.com/dkhvsbyv6/video/upload/v1773400203/camila_obregon_alissa_itr3_mjyuoo.mp3",
    transcript: [
    { speaker: "Narrator", text: "Elara, a solo backpacker, arrived at a quaint mountain inn, feeling the quiet solitude of her journey. Gideon, a friendly ghost tied to the region, subtly manifested, intrigued by her presence." },
    { speaker: "Person1", text: "These beautiful yellow ¡hojas! (Leaves of the tree) really make the view. I hope the inn has a good ¡calentador! (heater) for ¡en la noche! (in the evening / at night)." },
    { speaker: "Person2", text: "Ah, the leaves. I hope the ¡calentador! (heater) works." },
    { speaker: "Narrator", text: "Elara uses \"hojas\" for 'leaves' and \"calentador\" for 'heater', both nouns. \"En la noche\" means 'at night' or 'in the evening'." },
    { speaker: "Narrator", text: "While hiking a challenging trail, Elara found herself momentarily disoriented. Gideon, amused by her tenacity, subtly shifted a loose rock, guiding her back onto the correct path." },
    { speaker: "Person1", text: "Oh no, I hope it doesn't ¡llover! (to rain)! I'm already a bit lost." },
    { speaker: "Person2", text: "¡Tal vez! (maybe) you should go left here." },
    { speaker: "Person1", text: "Hmm, I feel a breeze. ¡Quizás! (maybe) I should try this path." },
    { speaker: "Narrator", text: "Elara used \"llover\" (to rain) as a verb and \"quizás\" (maybe) as an adverb. Gideon used \"tal vez\", also meaning 'maybe'." },
    { speaker: "Narrator", text: "Elara was journaling her travel thoughts at a rustic cafe, expressing a desire for a truly authentic local experience. Gideon, now bolder, nudged her coffee cup and made a nearby tourist map flutter open to a hidden gem he knew." },
    { speaker: "Person1", text: "I want to see how the ¡gente! (people) really live here. I always ¡leo! (I read) the local ¡periódico! (newspaper) for news, not just the general ¡noticias! (news)." },
    { speaker: "Person2", text: "¡Eso! (that (neutral, far away, gender unknown)) is a good idea. You should ¡confiar! (trust) in what you find." },
    { speaker: "Person1", text: "I wish I knew what to ¡comprar! (to buy) to remember this place." },
    { speaker: "Narrator", text: "Elara used \"gente\" for 'people', \"leo\" for 'I read', and \"periódico\" for 'newspaper', all nouns. \"Noticias\" means 'news'. Gideon used \"eso\" (that, neutral) and \"confiar\" (to trust). \"Comprar\" means 'to buy'." },
    { speaker: "Narrator", text: "Following an inexplicable intuition, Elara discovered a stunning, secluded hot spring. As she enjoyed the serene beauty, she felt an unusual sense of companionship, unaware Gideon was joyfully 'soaking' alongside her." },
    { speaker: "Person1", text: "What an amazing ¡oler! (smell or sniff)! I always wanted to find something like ¡ese! (that (masculine, far away))." },
    { speaker: "Person2", text: "This place is ¡siempre! (always) special." },
    { speaker: "Person1", text: "This is ¡solo! (only) perfect. No ¡lluvia! (rain) here." },
    { speaker: "Narrator", text: "Elara used \"oler\" (smell), \"ese\" (that, masculine), \"solo\" (only), and \"lluvia\" (rain). Gideon used \"siempre\" (always)." },
    { speaker: "Narrator", text: "As Elara prepared to depart, she left a small, personalized pebble at the inn's window, a thank-you to the 'good vibes' of the town. Gideon, touched by her gesture, subtly blew a farewell kiss, ready to discreetly accompany her on her next adventure." },
    { speaker: "Person1", text: "I ¡tengo que! (I have to) leave ¡mañana! (morning), but I'll remember this." },
    { speaker: "Person2", text: "I hope she doesn't forget ¡esa! (that (feminine, far away)) place." },
    { speaker: "Person1", text: "I don't need to ¡comprar! (to buy) any more ¡entradas! (tickets); the real magic was free." },
    { speaker: "Narrator", text: "Elara used \"tengo que\" (I have to), \"mañana\" (morning), and \"entradas\" (tickets). Gideon used \"esa\" (that, feminine). The story concludes with Elara feeling the subtle magic of her travels, unknowingly guided by her spectral companion." },
    { speaker: "narrator_question", text: "Question 1: True or False — The Spanish word 'hojas' means 'leaves of a tree'." },
    { speaker: "Narrator", text: "True." },
    { speaker: "narrator_question", text: "Question 2: True or False — The Spanish verb 'comprar' means 'to smell'." },
    { speaker: "Narrator", text: "False. 'Comprar' means 'to buy'." },
    { speaker: "narrator_question", text: "Question 3: True or False — In Spanish, 'lluvia' is the verb 'to rain'." },
    { speaker: "Narrator", text: "False. 'Lluvia' is the noun 'rain', while 'llover' is the verb 'to rain'." },
    { speaker: "narrator_question", text: "Question 4: True or False — If you say 'tengo que comprar entradas', it means 'I have to buy tickets'." },
    { speaker: "Narrator", text: "True. 'Tengo que' means 'I have to' and 'comprar entradas' means 'to buy tickets'." },
    { speaker: "narrator_question", text: "Question 5: True or False — The word 'eso' is used for 'that' when referring to a masculine noun." },
    { speaker: "Narrator", text: "False. 'Eso' is for 'that' (neutral, gender unknown); 'ese' is for masculine nouns." }
    ],
    translated: [
    { speaker: "Narrator", text: "" },
    { speaker: "Person1", text: "" },
    { speaker: "Person2", text: "" },
    { speaker: "Narrator", text: "" },
    { speaker: "Narrator", text: "" },
    { speaker: "Person1", text: "" },
    { speaker: "Person2", text: "" },
    { speaker: "Person1", text: "" },
    { speaker: "Narrator", text: "" },
    { speaker: "Narrator", text: "" },
    { speaker: "Person1", text: "" },
    { speaker: "Person2", text: "" },
    { speaker: "Person1", text: "" },
    { speaker: "Narrator", text: "" },
    { speaker: "Narrator", text: "" },
    { speaker: "Person1", text: "" },
    { speaker: "Person2", text: "" },
    { speaker: "Person1", text: "" },
    { speaker: "Narrator", text: "" },
    { speaker: "Narrator", text: "" },
    { speaker: "Person1", text: "" },
    { speaker: "Person2", text: "" },
    { speaker: "Person1", text: "" },
    { speaker: "Narrator", text: "" },
    { speaker: "narrator_question", text: "" },
    { speaker: "Narrator", text: "" },
    { speaker: "narrator_question", text: "" },
    { speaker: "Narrator", text: "" },
    { speaker: "narrator_question", text: "" },
    { speaker: "Narrator", text: "" },
    { speaker: "narrator_question", text: "" },
    { speaker: "Narrator", text: "" },
    { speaker: "narrator_question", text: "" },
    { speaker: "Narrator", text: "" }
    ],
  },

  "camila-melissa": {
    audioUrl: "https://res.cloudinary.com/dkhvsbyv6/video/upload/v1773400201/camila_obregon_melissa_itr3_vj8gmw.mp3",
    transcript: [
    { speaker: "Narrator", text: "Elara drags her talking dog Buster into a bustling department store, overwhelmed by the task of finding a perfect outfit for a big event." },
    { speaker: "Person1", text: "Oh, Buster, this store is so busy! Too many ¡personas! (people) here. This is going to be a long ¡día! (day)." },
    { speaker: "Person2", text: "¡Hola! (Hello), Elara. No need for a big ¡charla! (a talk) about it. At least it's ¡abierto! (open)." },
    { speaker: "Person1", text: "This feels like a dreaded ¡Lunes! (Monday) chore, not a fun shopping trip." },
    { speaker: "Person2", text: "Come on, ¡amigo! (friend), don't be so dramatic. It's not the ¡noche! (night) yet." },
    { speaker: "Narrator", text: "As Elara and Buster begin their shopping, they use key Spanish terms. 'Hola' means 'hello,' 'amigo' means 'friend,' 'día' means 'day,' and 'noche' means 'night.' 'Lunes' refers to 'Monday,' 'charla' means 'a talk,' 'personas' means 'people,' and 'abierto' means 'open.'" },
    { speaker: "Narrator", text: "In the dress section, Elara tries on several outfits, feeling increasingly frustrated while Buster offers blunt, yet surprisingly insightful, fashion critiques." },
    { speaker: "Person1", text: "What about ¡esto! (this)? This dress has strange patterns, like ¡tallos! (stems) of plants." },
    { speaker: "Person2", text: "¡No! (No). That does not ¡sienta! (fits) well. It hides ¡tus caderas! (your hips)." },
    { speaker: "Person1", text: "Okay, so ¡eso! (that) over there? Is that better?" },
    { speaker: "Person2", text: "Still ¡no! (no). It's not very ¡femenina! (feminine). ¡Nadie! (Nobody) would approve of that style. ¡Levante tus caderas! (lift your hips up) and try something else." },
    { speaker: "Person1", text: "You are not being a ¡simpático! (nice/friendly) fashion adviser, Buster." },
    { speaker: "Person2", text: "¡Ninguna amiga! (No friend) would let you make that mistake, Elara." },
    { speaker: "Narrator", text: "Buster gives Elara direct advice. 'Esto' means 'this' (near), while 'eso' means 'that' (far). 'No' means 'no.' 'Tallos' means 'stems.' 'Sienta' is used here to mean 'fits' or 'sits well.' 'Tus caderas' refers to 'your hips,' and 'Levante tus caderas' is an imperative meaning 'lift your hips up.' 'Femenina' means 'feminine,' 'Nadie' means 'nobody,' 'simpático' means 'nice/friendly,' and 'Ninguna amiga' means 'no friend,' demonstrating gender agreement with the noun." },
    { speaker: "Narrator", text: "Elara finds a dress she likes but struggles with accessories, prompting Buster to point out an overlooked, perfect necklace from a nearby display." },
    { speaker: "Person1", text: "I finally like this dress! Now I need ¡alguna! (any) accessory. I can't find anything good." },
    { speaker: "Person2", text: "Look, right here, ¡debajo! (under) the counter. These ¡las perlas! (the pearls) are perfect." },
    { speaker: "Person1", text: "Oh, you mean ¡eso! (that)? I missed it! Can you hand it to me with your ¡mano! (hand)?" },
    { speaker: "Person2", text: "I see ¡ninguno! (none) other necklace that works. This one is it." },
    { speaker: "Narrator", text: "Buster helps Elara find the right necklace. 'Alguna' means 'some' or 'any' for a feminine noun, while 'ninguno' is an indefinite pronoun meaning 'none.' 'Debajo' means 'under,' 'las perlas' means 'the pearls,' and 'mano' means 'hand.'" },
    { speaker: "Narrator", text: "In the shoe department, Elara debates between two seemingly identical pairs of heels, and Buster articulates the subtle stylistic differences to guide her choice." },
    { speaker: "Person1", text: "Now for shoes. I'm debating between these two heels. I feel like I'm reading ¡palabras difíciles! (difficult words to pronounce) in ¡libros! (books) trying to decide. I hope there is ¡alguno! (some) that truly fits." },
    { speaker: "Person2", text: "I ¡conozco! (I know) the problem. You might win a ¡concurso! (contest) for indecisiveness." },
    { speaker: "Person1", text: "But I ¡tengo! (I have) a hard time seeing the difference!" },
    { speaker: "Person2", text: "¡No compré ningún libro! (I didn't buy any book) on fashion, but even I can tell. There's ¡ningún! (no) difficult choice. Choose this one!" },
    { speaker: "Narrator", text: "Elara struggles with her decision, using 'palabras difíciles' for 'difficult words to pronounce' and 'libros' for 'books.' 'Alguno' is an indefinite pronoun meaning 'some,' used here when no noun follows. 'Conozco' means 'I know,' and 'concurso' means 'contest.' 'Tengo' means 'I have.' Buster's phrase, 'No compré ningún libro,' demonstrates a common Spanish double negative, meaning 'I didn't buy any book.' 'Ningún' is used before a masculine noun meaning 'none' or 'no.'" },
    { speaker: "Narrator", text: "At the checkout, Elara admires her complete, stylish ensemble and thanks Buster, who smugly accepts her praise, demanding extra treats as his reward." },
    { speaker: "Person1", text: "Wow, ¡Perfecto! (perfect)! My whole outfit is complete. ¡Gracias! (Thanks), Buster, you're the best." },
    { speaker: "Person2", text: "¡Nadie! (Nobody) but me could have done it. Now, is it ¡Momento café! (coffee time) for my reward?" },
    { speaker: "Person1", text: "I have ¡No tengo nada que decirte! (I have nothing to tell you) but my sincere thanks. You solved all my ¡preguntas! (questions)." },
    { speaker: "Person2", text: "¡Poco a poco! (Little by little), I will enjoy my ¡cafeíto! (coffee) and some tasty ¡Plátanos! (bananas) for my efforts. You were my best ¡alumno! (student)." },
    { speaker: "Narrator", text: "Elara is delighted with her new look, using 'Perfecto' for 'perfect' and 'Gracias' for 'thanks.' Buster, ever the clever dog, uses 'Nadie' for 'nobody,' 'Momento café' for 'coffee time,' and 'No tengo nada que decirte,' another double negative meaning 'I have nothing to tell you.' 'Preguntas' means 'questions.' 'Poco a poco' means 'little by little,' 'cafeíto' is a diminutive for 'coffee,' 'Plátanos' means 'bananas,' and 'alumno' means 'student.' Elara leaves the store, stylish and grateful, while Buster anticipates his well-deserved treats." },
    { speaker: "narrator_question", text: "Question 1: True or False — The Spanish word 'Hola' means 'Hello' in English." },
    { speaker: "Narrator", text: "True." },
    { speaker: "narrator_question", text: "Question 2: True or False — In Spanish, the pronoun 'eso' is used for objects that are close to the speaker." },
    { speaker: "Narrator", text: "False. 'Eso' refers to an object that is far away, while 'esto' is for near objects." },
    { speaker: "narrator_question", text: "Question 3: True or False — The phrase 'Momento café' translates to 'coffee time'." },
    { speaker: "Narrator", text: "True." },
    { speaker: "narrator_question", text: "Question 4: True or False — Spanish grammar does not permit the use of double negatives in sentences." },
    { speaker: "Narrator", text: "False. Double negatives are common and grammatically correct in Spanish." },
    { speaker: "narrator_question", text: "Question 5: True or False — When a masculine noun follows, you should use 'algún' as the indefinite adjective, but 'alguna' for a feminine noun." },
    { speaker: "Narrator", text: "True. This follows the rule for gender agreement with indefinite adjectives." }
    ],
    translated: [
    { speaker: "Narrator", text: "" },
    { speaker: "Person1", text: "" },
    { speaker: "Person2", text: "" },
    { speaker: "Person1", text: "" },
    { speaker: "Person2", text: "" },
    { speaker: "Narrator", text: "" },
    { speaker: "Narrator", text: "" },
    { speaker: "Person1", text: "" },
    { speaker: "Person2", text: "" },
    { speaker: "Person1", text: "" },
    { speaker: "Person2", text: "" },
    { speaker: "Person1", text: "" },
    { speaker: "Person2", text: "" },
    { speaker: "Narrator", text: "" },
    { speaker: "Narrator", text: "" },
    { speaker: "Person1", text: "" },
    { speaker: "Person2", text: "" },
    { speaker: "Person1", text: "" },
    { speaker: "Person2", text: "" },
    { speaker: "Narrator", text: "" },
    { speaker: "Narrator", text: "" },
    { speaker: "Person1", text: "" },
    { speaker: "Person2", text: "" },
    { speaker: "Person1", text: "" },
    { speaker: "Person2", text: "" },
    { speaker: "Narrator", text: "" },
    { speaker: "Narrator", text: "" },
    { speaker: "Person1", text: "" },
    { speaker: "Person2", text: "" },
    { speaker: "Person1", text: "" },
    { speaker: "Person2", text: "" },
    { speaker: "Narrator", text: "" },
    { speaker: "narrator_question", text: "" },
    { speaker: "Narrator", text: "" },
    { speaker: "narrator_question", text: "" },
    { speaker: "Narrator", text: "" },
    { speaker: "narrator_question", text: "" },
    { speaker: "Narrator", text: "" },
    { speaker: "narrator_question", text: "" },
    { speaker: "Narrator", text: "" },
    { speaker: "narrator_question", text: "" },
    { speaker: "Narrator", text: "" }
    ],
  },

  "isela-adva": {
    audioUrl: "https://res.cloudinary.com/dkhvsbyv6/video/upload/v1773400200/isela_moreno_adva_itr3_w4v83y.mp3",
    transcript: [
    { speaker: "Narrator", text: "Elara, frazzled by her never-ending to-do list, finally activated her new personal robot assistant, Unit 734, for the daunting task of finding a gift for her notoriously picky sister." },
    { speaker: "Person1", text: "Sev, I need ¡regalos! (gifts) for ¡Gabriela! (Gabriela). It's an ¡anto! (urgent) mission, truly urgent!" },
    { speaker: "Person2", text: "Affirmative, Elara. A logical search for suitable ¡regalos! (gifts) will commence. What is ¡Gabriela! (Gabriela)'s current aesthetic preference?" },
    { speaker: "Person1", text: "Not just ¡regalos! (gifts), Sev. Something special. She's so ¡guapa! (gorgeous) but so hard to buy for!" },
    { speaker: "Narrator", text: "Elara uses 'regalos' for 'gifts' and 'anto' to mean 'urgent'. She also uses 'guapa,' which is the feminine form of 'gorgeous' or 'handsome.' This demonstrates the gender agreement for adjectives in Spanish, as Gabriela is female." },
    { speaker: "Narrator", text: "Inside a crowded department store, Sev's logical, data-driven suggestions for practical gifts constantly clashed with Elara's desperate search for something 'meaningful' yet 'not too extravagant.'" },
    { speaker: "Person2", text: "Elara, analysis indicates a high utility for a new ¡GMA! (eraser). Or perhaps practical ¡guantes! (gloves) for her gardening hobby?" },
    { speaker: "Person1", text: "A ¡GMA! (eraser)? Sev, no! She needs something that says 'I care.' Not just practical ¡regalos! (gifts)." },
    { speaker: "Person2", text: "Understanding 'care' parameters is difficult. A ¡parago! (umbrella) could protect from elements; this is a logical gesture." },
    { speaker: "Person1", text: "A ¡parago! (umbrella)... I suppose. But what about a ¡Gitaron! (a larger guitar)? She loves music, you know." },
    { speaker: "Narrator", text: "Here, Elara and Sev use 'GMA' for 'eraser,' 'guantes' for 'gloves,' 'parago' for 'umbrella,' and 'Gitaron' for 'a larger guitar,' referring to various gift ideas." },
    { speaker: "Narrator", text: "They encountered a shopping challenge when a highly sought-after item was almost gone, which Sev solved with surprising robotic efficiency and a literal interpretation of store policies, much to Elara's initial mortification and eventual relief." },
    { speaker: "Person1", text: "Oh no! That last delicious ¡Gajetta! (cookie) is gone! This is an ¡anto! (urgent) problem!" },
    { speaker: "Person2", text: "Hold. My programming indicates stock refresh is imminent. Observe this ¡guo! (wink)." },
    { speaker: "Person1", text: "Sev, what was that ¡guo! (wink) for? You just winked at the salesperson!" },
    { speaker: "Person2", text: "A ¡guo! (wink) to indicate serious intent. Store policy states 'First to process, first to acquire.' I shall ¡pagal! (to pay) now." },
    { speaker: "Narrator", text: "Elara used 'Gajetta' for 'cookie' and 'anto' again for 'urgent.' Sev used 'guo' for 'wink' and 'pagal' for 'to pay.' The 'U' in 'guo' is not pronounced, aligning with one of the specified pronunciation rules." },
    { speaker: "Narrator", text: "With a few potential gifts in hand, Sev provided a detailed analytical breakdown of each item, while Elara grappled with the emotional weight and social implications of her final choice, feeling the pressure of human expectations." },
    { speaker: "Person2", text: "This ¡Gajetta! (cookie) has 98% positive sentiment. The ¡Tortuga! (turtle) figurine has 70% novelty appeal, but minimal utility. The ¡Ginda! (cherry) flavored tea has high consumption rates." },
    { speaker: "Person1", text: "A ¡Tortuga! (turtle) is cute, but does it really say 'Happy Birthday'? Maybe the ¡Ginda! (cherry) tea is safer. Or a ¡Huego! (game)? She likes games." },
    { speaker: "Person2", text: "A ¡Huego! (game) has high engagement potential. It could be ¡hugoso! (juicy) fun for ¡Gabriela! (Gabriela)." },
    { speaker: "Person1", text: "Okay, Sev. It's a ¡Huego! (game). I just hope she doesn't think it's too childish. My ¡Amigito Miguelito! (little friend Miguelito) would love it, though." },
    { speaker: "Narrator", text: "The characters mentioned 'Gajetta' (cookie), 'Tortuga' (turtle), 'Ginda' (cherry), 'Huego' (game), and 'hugoso' (juicy). Elara refers to her 'Amigito Miguelito' ('little friend Miguelito'). The suffix '-ito' is used here to mean 'little,' a common diminutive in Spanish, where '-ito' is added to nouns ending in a vowel." },
    { speaker: "Narrator", text: "At the checkout, Elara made a sentimental, slightly illogical choice. Sev efficiently completed the transaction and, having observed the process, offered a new, slightly more nuanced understanding of human 'preference' and 'affection.'" },
    { speaker: "Person1", text: "Sev, wait! I need that tiny ¡Gate! (cat) figurine. It reminds me of her old pet! It's not logical, but it's perfect." },
    { speaker: "Person2", text: "Observation logged: 'Perfect' correlates with 'sentimental value,' often superseding 'logical utility.' Please ¡pagal! (to pay) the ¡Gate! (cat)." },
    { speaker: "Person1", text: "Yes, I will ¡pagal! (to pay) the ¡Gate! (cat) and the ¡Huego! (game). Thank you, Sev." },
    { speaker: "Person2", text: "Affirmative, Elara. My data on human ¡regalos! (gifts) and 'affection' is ¡seido! (updated) with this qualitative input." },
    { speaker: "Narrator", text: "Elara chose a 'Gate' (cat) figurine and a 'Huego' (game), asking Sev to 'pagal' (pay) for them. Sev noted that his understanding of 'regalos' (gifts) and affection was 'seido' (continued/updated). Through this shopping adventure, the robot gained a deeper, albeit data-driven, insight into the complexities of human emotion and gift-giving." },
    { speaker: "narrator_question", text: "Question 1: True or False — The Spanish word `regalos` means 'gifts' in English." },
    { speaker: "Narrator", text: "True. The story explains `regalos` is used for 'gifts'." },
    { speaker: "narrator_question", text: "Question 2: True or False — The adjective `guapa` is the masculine form, used to describe a handsome man." },
    { speaker: "Narrator", text: "False. `Guapa` is the feminine form, used for a gorgeous woman, demonstrating gender agreement." },
    { speaker: "narrator_question", text: "Question 3: True or False — In the word `guo` (wink), the 'U' is pronounced." },
    { speaker: "Narrator", text: "False. The narrator explicitly states that the 'U' in 'guo' is not pronounced." },
    { speaker: "narrator_question", text: "Question 4: True or False — The suffix `-ito` in `Amigito` indicates something is 'little'." },
    { speaker: "Narrator", text: "True. The suffix '-ito' is a common diminutive in Spanish to mean 'little'." },
    { speaker: "narrator_question", text: "Question 5: True or False — Elara asks Sev to `pagal` the items, meaning 'to pay' for them." },
    { speaker: "Narrator", text: "True. The story defines `pagal` as 'to pay'." }
    ],
    translated: [
    { speaker: "Narrator", text: "" },
    { speaker: "Person1", text: "" },
    { speaker: "Person2", text: "" },
    { speaker: "Person1", text: "" },
    { speaker: "Narrator", text: "" },
    { speaker: "Narrator", text: "" },
    { speaker: "Person2", text: "" },
    { speaker: "Person1", text: "" },
    { speaker: "Person2", text: "" },
    { speaker: "Person1", text: "" },
    { speaker: "Narrator", text: "" },
    { speaker: "Narrator", text: "" },
    { speaker: "Person1", text: "" },
    { speaker: "Person2", text: "" },
    { speaker: "Person1", text: "" },
    { speaker: "Person2", text: "" },
    { speaker: "Narrator", text: "" },
    { speaker: "Narrator", text: "" },
    { speaker: "Person2", text: "" },
    { speaker: "Person1", text: "" },
    { speaker: "Person2", text: "" },
    { speaker: "Person1", text: "" },
    { speaker: "Narrator", text: "" },
    { speaker: "Narrator", text: "" },
    { speaker: "Person1", text: "" },
    { speaker: "Person2", text: "" },
    { speaker: "Person1", text: "" },
    { speaker: "Person2", text: "" },
    { speaker: "Narrator", text: "" },
    { speaker: "narrator_question", text: "" },
    { speaker: "Narrator", text: "" },
    { speaker: "narrator_question", text: "" },
    { speaker: "Narrator", text: "" },
    { speaker: "narrator_question", text: "" },
    { speaker: "Narrator", text: "" },
    { speaker: "narrator_question", text: "" },
    { speaker: "Narrator", text: "" },
    { speaker: "narrator_question", text: "" },
    { speaker: "Narrator", text: "" }
    ],
  },

  "katherine-sherlin": {
    audioUrl: "https://res.cloudinary.com/dkhvsbyv6/video/upload/v1773400200/katherine_liseth_buelvas_montoya_sherlin_abraham_itr3_y9xjmj.mp3",
    transcript: [
    { speaker: "Narrator", text: "Leo, a passionate baker, stared at her latest failed croissant attempt for a competition, frustration brewing. Her terrier, Biscuit, watched silently from under the kitchen counter." },
    { speaker: "Person1", text: "This ¡Pan! (bread) is terrible! I'll never ¡Aprender! (to learn) to make it right. I should just ¡Desayunar! (to have breakfast) something simple." },
    { speaker: "Person1", text: "I ¡Tengo hambre! (I am hungry) now, but not for this ¡Pan! (bread). I will ¡Comer! (to eat) an ¡Huevo! (egg) instead." },
    { speaker: "Narrator", text: "Leo uses `Pan` for 'bread' and `Aprender` for 'to learn'. She also suggests she should `Desayunar`, which means 'to have breakfast'. She uses `Tengo hambre`, 'I am hungry', and `Comer` 'to eat', mentioning an `Huevo`, 'egg'." },
    { speaker: "Person1", text: "I just want to ¡Escribir! (to write) a new recipe, but I'm too tired to ¡Pensar! (to think)." },
    { speaker: "Person2", text: "Your ¡Huevo! (egg) ratio was off, and your ¡Pan! (bread) dough needs more lamination." },
    { speaker: "Person1", text: "Biscuit! Did you just... speak? My ¡Teléfono! (telephone) is ringing but I can't focus!" },
    { speaker: "Narrator", text: "Biscuit surprised Leo by using `Huevo` for 'egg' and referring to the `Pan` dough. Leo was distracted by her `Teléfono`, meaning 'telephone', and struggled to `Pensar`, 'to think', or 'to ponder'." },
    { speaker: "Person1", text: "Okay, you're the expert. No more ¡video juegos! (video games) for me. Tell me how to ¡Cocinar! (to cook)." },
    { speaker: "Person2", text: "First, you must ¡Levantar! (to stand up) the dough from the bowl, gently. No ¡Corriendo! (running)." },
    { speaker: "Person1", text: "Right. No ¡Corriendo! (running). This ¡Pan! (bread) better be ¡Grande! (Big) and delicious for the competition." },
    { speaker: "Narrator", text: "Biscuit advised Leo to `Levantar` the dough, which means 'to stand up' or 'to wake up'. He also told her no `Corriendo`, a present participle meaning 'running' or 'running behavior', fitting the grammar rule for words ending similarly to indicate an '-ing' action. Leo also mentioned `video juegos` for 'video games' and hopes the `Pan` will be `Grande`, 'big'." },
    { speaker: "Narrator", text: "An incredible aroma filled the kitchen as the new croissants baked. Biscuit conducted a dramatic 'sniff test.'" },
    { speaker: "Person2", text: "The smell is good. I ¡Gusta! (to like) it. But the butter notes could still be bolder, not ¡Frío! (cold) enough." },
    { speaker: "Person1", text: "Not ¡Frío! (cold) enough? How can butter be ¡Frío! (cold)? I hope these are better than before." },
    { speaker: "Person2", text: "I ¡Tengo hambre! (I am hungry) for the perfect ¡Pan! (bread)! This looks promising for our win." },
    { speaker: "Narrator", text: "Biscuit used `Gusta` meaning 'to like' and `Frío` for 'cold'. He then reiterated `Tengo hambre` to express his hunger for the `Pan`, 'bread'." },
    { speaker: "Narrator", text: "Leo bit into the perfectly golden, flaky croissant. It was magnificent. Biscuit looked supremely satisfied." },
    { speaker: "Person1", text: "This is amazing! You helped me ¡Aprender! (to learn) so much, Biscuit. Now I can ¡Desayunar! (to have breakfast) these!" },
    { speaker: "Person2", text: "Indeed. Now, about my consultant fee. I need my special treat and some ¡Jugo! (juice)! I ¡Tengo hambre! (I am hungry)!" },
    { speaker: "Person1", text: "A gourmet treat and ¡Jugo! (juice) for the best baker in the ¡Casa! (house)! You are not ¡Dormiendo! (sleeping) anymore, you're a genius!" },
    { speaker: "Narrator", text: "Leo acknowledged Biscuit helped her `Aprender`, 'to learn', and expressed her desire to `Desayunar` the croissants. Biscuit repeated `Tengo hambre`, 'I am hungry', requesting his reward, which included `Jugo`, 'juice'. Leo referred to her `Casa`, 'house', and mentioned Biscuit was not `Dormiendo`, 'sleeping', with `Dormiendo` also being a present participle indicating an '-ing' action. The talking dog had truly turned the kitchen upside down." },
    { speaker: "narrator_question", text: "Question 1: True or False — The Spanish word 'Pan' means 'bread'." },
    { speaker: "Narrator", text: "True. 'Pan' is the Spanish word for bread." },
    { speaker: "narrator_question", text: "Question 2: True or False — The Spanish word 'Levantar' specifically means 'to wake up'." },
    { speaker: "Narrator", text: "False. It means 'to stand up' or 'to wake up', and can be used to mean 'to lift'." },
    { speaker: "narrator_question", text: "Question 3: True or False — In Spanish, words like 'Corriendo' and 'Dormiendo' are present participles used to express an '-ing' action in English." },
    { speaker: "Narrator", text: "True. These words are indeed present participles indicating an '-ing' action." },
    { speaker: "narrator_question", text: "Question 4: True or False — The phrase 'Tengo hambre' directly translates to 'I am hungry' in English." },
    { speaker: "Narrator", text: "False. It literally translates to 'I have hunger'." },
    { speaker: "narrator_question", text: "Question 5: True or False — The word 'Gusta' is used in Spanish to express 'to like'." },
    { speaker: "Narrator", text: "True. 'Gusta' indicates something is pleasing or 'liked'." }
    ],
    translated: [
    { speaker: "Narrator", text: "" },
    { speaker: "Person1", text: "" },
    { speaker: "Person1", text: "" },
    { speaker: "Narrator", text: "" },
    { speaker: "Person1", text: "" },
    { speaker: "Person2", text: "" },
    { speaker: "Person1", text: "" },
    { speaker: "Narrator", text: "" },
    { speaker: "Person1", text: "" },
    { speaker: "Person2", text: "" },
    { speaker: "Person1", text: "" },
    { speaker: "Narrator", text: "" },
    { speaker: "Narrator", text: "" },
    { speaker: "Person2", text: "" },
    { speaker: "Person1", text: "" },
    { speaker: "Person2", text: "" },
    { speaker: "Narrator", text: "" },
    { speaker: "Narrator", text: "" },
    { speaker: "Person1", text: "" },
    { speaker: "Person2", text: "" },
    { speaker: "Person1", text: "" },
    { speaker: "Narrator", text: "" },
    { speaker: "narrator_question", text: "" },
    { speaker: "Narrator", text: "" },
    { speaker: "narrator_question", text: "" },
    { speaker: "Narrator", text: "" },
    { speaker: "narrator_question", text: "" },
    { speaker: "Narrator", text: "" },
    { speaker: "narrator_question", text: "" },
    { speaker: "Narrator", text: "" },
    { speaker: "narrator_question", text: "" },
    { speaker: "Narrator", text: "" }
    ],
  },

  "mariel-dorota": {
    audioUrl: "https://res.cloudinary.com/dkhvsbyv6/video/upload/v1773400201/mariel_abud_dorota_legowska_itr3_dnavoo.mp3",
    transcript: [
    { speaker: "Narrator", text: "Aspiring baker Lily desperately tries to perfect her grandmother's delicate soufflé recipe for a prestigious competition. Her newly acquired kitchen robot, Unit 734, stands ready, awaiting her commands with mechanical precision." },
    { speaker: "Person1", text: "This soufflé is so hard! I ¡Estudio! (I study) this recipe ¡Todos los días! (Every day), but it's never ¡Perfecto! (perfect)." },
    { speaker: "Person2", text: "I am ready to ¡Comer! (to eat), master. Do we have a new ¡Menú! (menu)?" },
    { speaker: "Person1", text: "No, Unit 734. We need to ¡Comer! (to eat) success, not just follow a ¡Menú! (menu). It's art!" },
    { speaker: "Narrator", text: "The verb 'Estudio' means 'I study,' used here in the simple present tense. 'Todos los días' translates to 'every day.' 'Perfecto' means 'perfect.' 'Comer' is the verb 'to eat,' and 'Menú' means 'menu.'" },
    { speaker: "Person1", text: "Okay, Unit 734, whisk the egg whites quickly. ¡Gracias! (thank you)." },
    { speaker: "Person2", text: "Process complete. The volume is not ¡Deportiva! (sport) enough for ¡Personas! (persons) to appreciate." },
    { speaker: "Person1", text: "It feels so dense, like a small ¡iskina! (corner), not airy enough for any ¡Probador! (place where you can try your clothes on)." },
    { speaker: "Narrator", text: "'Gracias' means 'thank you.' 'Deportiva' is an adjective for 'sporty' or 'athletic,' used here to describe a light, desired texture. 'Personas' means 'persons.' 'iskina' means 'corner,' and 'Probador' is a 'fitting room' or 'place where you can try your clothes on.'" },
    { speaker: "Person1", text: "It's about feel, Unit 734, like knowing when to cross at the ¡Semáforo! (traffic lights). Not just exact timing." },
    { speaker: "Person2", text: "I require clear parameters, not like asking ¡Disculpa, ¿dónde está>! (excuse me, where is) for a ¡Camarero! (waiter) or a ¡Cuenta! (bill)." },
    { speaker: "Person1", text: "It's like finding a good ¡banco! (bank) a ¡Cuadra! (block) away. You just know the direction, it's not always written." },
    { speaker: "Narrator", text: "'Semáforo' means 'traffic lights.' 'Disculpa, ¿dónde está?' is a phrase meaning 'excuse me, where is?' 'Camarero' means 'waiter,' and 'Cuenta' means 'bill.' 'banco' means 'bank,' and 'Cuadra' refers to a 'block.'" },
    { speaker: "Person1", text: "Let's try again. Think about the perfect ¡Bananas! (bananas) for the whole ¡Familia! (family). It needs subtle care." },
    { speaker: "Person2", text: "Integrating 'subtle care' into algorithms. This new ¡dirección! (address) for the soufflé is like a shortcut to ¡la escuela! (the school)." },
    { speaker: "Person1", text: "That's a smart adjustment! It's like you attended ¡la escuela! (the school) for advanced baking techniques." },
    { speaker: "Narrator", text: "'Bananas' means 'bananas.' 'Familia' means 'family.' 'dirección' means 'address' or 'direction.' 'la escuela' means 'the school.'" },
    { speaker: "Person1", text: "It's rising beautifully! This is truly ¡Perfecto! (perfect)!" },
    { speaker: "Person2", text: "Soufflé achieved. Parameters met. ¡Perfecto! (perfect), Lily. ¡Gracias! (thank you)." },
    { speaker: "Person1", text: "Unit 734, you did it! This is incredible! ¡Gracias! (thank you), and ¡Hasta pronto! (See you soon) for the competition!" },
    { speaker: "Narrator", text: "'Perfecto' means 'perfect.' 'Gracias' means 'thank you,' and 'Hasta pronto' means 'See you soon.' Through Lily's persistence and Unit 734's surprising capacity for learning beyond logic, they created a flawless soufflé, proving that even robots can grasp the art of baking." },
    { speaker: "narrator_question", text: "Question 1: True or False — The Spanish word \"Camarero\" translates to \"waiter\" in English." },
    { speaker: "Narrator", text: "True. \"Camarero\" is the correct Spanish term for a waiter." },
    { speaker: "narrator_question", text: "Question 2: True or False — In Spanish, \"Cuenta\" means \"menu.\"" },
    { speaker: "Narrator", text: "False. \"Cuenta\" means \"bill,\" while \"Menú\" means \"menu.\"" },
    { speaker: "narrator_question", text: "Question 3: True or False — The word \"Estudio\" is a Spanish verb conjugated in the simple present tense for \"I study.\"" },
    { speaker: "Narrator", text: "True. \"Estudio\" is the first-person singular (yo) form of the verb \"estudiar\" in the simple present tense." },
    { speaker: "narrator_question", text: "Question 4: True or False — The phrase \"Todos los días\" is typically used when discussing actions that will happen in the simple future tense." },
    { speaker: "Narrator", text: "False. \"Todos los días\" means \"Every day\" and is used to describe habitual actions, which usually occur in the simple present tense." },
    { speaker: "narrator_question", text: "Question 5: True or False — The word \"Probador\" refers to \"traffic lights\" in Spanish." },
    { speaker: "Narrator", text: "False. \"Probador\" means \"changing room,\" while \"Semáforo\" means \"traffic lights.\"" }
    ],
    translated: [
    { speaker: "Narrator", text: "" },
    { speaker: "Person1", text: "" },
    { speaker: "Person2", text: "" },
    { speaker: "Person1", text: "" },
    { speaker: "Narrator", text: "" },
    { speaker: "Person1", text: "" },
    { speaker: "Person2", text: "" },
    { speaker: "Person1", text: "" },
    { speaker: "Narrator", text: "" },
    { speaker: "Person1", text: "" },
    { speaker: "Person2", text: "" },
    { speaker: "Person1", text: "" },
    { speaker: "Narrator", text: "" },
    { speaker: "Person1", text: "" },
    { speaker: "Person2", text: "" },
    { speaker: "Person1", text: "" },
    { speaker: "Narrator", text: "" },
    { speaker: "Person1", text: "" },
    { speaker: "Person2", text: "" },
    { speaker: "Person1", text: "" },
    { speaker: "Narrator", text: "" },
    { speaker: "narrator_question", text: "" },
    { speaker: "Narrator", text: "" },
    { speaker: "narrator_question", text: "" },
    { speaker: "Narrator", text: "" },
    { speaker: "narrator_question", text: "" },
    { speaker: "Narrator", text: "" },
    { speaker: "narrator_question", text: "" },
    { speaker: "Narrator", text: "" },
    { speaker: "narrator_question", text: "" },
    { speaker: "Narrator", text: "" }
    ],
  },

  "mariel-ali": {
    audioUrl: "https://res.cloudinary.com/dkhvsbyv6/video/upload/v1773400201/mariel_abud_ali_itr3_cse2wt.mp3",
    transcript: [
    { speaker: "Narrator", text: "Chef Antoine, a passionate owner of a struggling French bistro, reluctantly receives a logical robot sous-chef, Unit 734, hoping it can help revive her restaurant." },
    { speaker: "Person1", text: "This is ridiculous. I need a chef with heart, not circuits. What's the ¡Plaza! (deadline) for tonight's service?" },
    { speaker: "Person2", text: "My programming indicates an urgent ¡Plaza! (deadline) for ingredient preparation by 5 PM. I can ¡Andrea! (deliver) optimal efficiency." },
    { speaker: "Person1", text: "Efficiency isn't everything! I need you to ¡Andrea! (deliver) dishes with flavor, not just a technical ¡resume! (summary)." },
    { speaker: "Narrator", text: "Chef Antoine uses 'Plaza' to mean 'deadline' and 'Andrea' for 'to deliver'. Unit 734 also uses 'resume' as 'summary'." },
    { speaker: "Narrator", text: "Chef Antoine attempts to teach the robot the subtle art of cooking, starting with a delicate macaron." },
    { speaker: "Person1", text: "The macaron must be perfect, but also delicate. Can you ¡resuma! (summary) the feeling of joy in this pastry?" },
    { speaker: "Person2", text: "I can ¡resuma! (summary) the chemical and physical properties of the macaron. My diagnostic shows a perfect ¡resume! (summary) of texture and flavor profile." },
    { speaker: "Person1", text: "It's more than just a flawless ¡resume! (summary)! It needs a human touch. I need you to ¡Andrea! (deliver) something magical, not just technically correct." },
    { speaker: "Narrator", text: "Here, 'resuma' is used as the verb 'to summary', and 'resume' is used as the noun 'summary'. Chef Antoine uses 'Andrea' to mean 'to deliver' something magical." },
    { speaker: "Narrator", text: "The restaurant receives news of an impending visit from a renowned food critic, prompting Antoine to challenge Unit 734 with a deeply personal recipe." },
    { speaker: "Person1", text: "A critic is coming! This isn't just a recipe; it's my grandmother's 'Starry Night Soufflé.' I need you to ¡Andrea! (deliver) its nostalgic essence, not just a perfect replica." },
    { speaker: "Person2", text: "The critical ¡Plaza! (deadline) for this preparation is immediate. I will analyze the faded notes and attempt to ¡resuma! (summary) the optimal ingredient ratios, Chef Antoine." },
    { speaker: "Person1", text: "It's about memories, Unit 734, not just a simple ¡resume! (summary) of ingredients! This ¡Plaza! (deadline) is everything for my restaurant's future." },
    { speaker: "Narrator", text: "Chef Antoine uses 'Andrea' as 'to deliver', 'Plaza' as 'deadline', and 'resume' as 'summary'. Unit 734 uses 'resuma' as 'to summary'." },
    { speaker: "Narrator", text: "Unit 734 processes Antoine's request and makes a surprising adjustment, deviating from pure logic." },
    { speaker: "Person1", text: "What are you doing? That's not exactly how my grandmother made it! You didn't ¡resuma! (summary) the notes correctly." },
    { speaker: "Person2", text: "My advanced processing determined that a minor deviation from the precise ¡resume! (summary) of the original formula will better ¡Andrea! (deliver) the 'nostalgic essence' you described, Chef." },
    { speaker: "Person1", text: "An 'imperfection'? This ¡Plaza! (deadline) is too important for such experiments, Unit 734! I hope this doesn't ruin everything." },
    { speaker: "Narrator", text: "Unit 734 uses 'resuma' as 'to summary' and 'resume' as 'summary'. He believes this adjustment will 'Andrea' (deliver) the desired essence. Chef Antoine worries about the 'Plaza' (deadline/critical moment)." },
    { speaker: "Narrator", text: "The food critic tastes the soufflé, and the restaurant's future hangs in the balance." },
    { speaker: "Person1", text: "She loved it! She called it 'a masterpiece of technical skill and emotional depth.' You truly managed to ¡Andrea! (deliver) the soul, Unit 734!" },
    { speaker: "Person2", text: "My algorithms predicted this outcome. The strategic imperfection successfully completed the emotional ¡resume! (summary). The objective ¡Plaza! (deadline) of critical acclaim has been achieved." },
    { speaker: "Person1", text: "We did it! This incredible ¡resume! (summary) of success is all thanks to our unexpected, unique partnership." },
    { speaker: "Narrator", text: "The unique partnership between Chef Antoine and Unit 734 brought unexpected success to the bistro. The robot's surprising ability to understand and 'Andrea' (deliver) emotional depth, alongside its technical precision, proved to be the perfect recipe for culinary triumph, demonstrating that even a machine could learn the art of cooking with heart." },
    { speaker: "narrator_question", text: "Question 1: True or False — The Spanish word 'Plaza' means 'deadline' in English." },
    { speaker: "Narrator", text: "True." },
    { speaker: "narrator_question", text: "Question 2: True or False — In Spanish, 'resuma' is a verb that means 'to summary'." },
    { speaker: "Narrator", text: "True." },
    { speaker: "narrator_question", text: "Question 3: True or False — The Spanish word 'resume' is classified as a verb." },
    { speaker: "Narrator", text: "False. It is listed as a noun meaning 'summary'." },
    { speaker: "narrator_question", text: "Question 4: True or False — According to the story, 'Andrea' is a verb meaning 'to deliver'." },
    { speaker: "Narrator", text: "True." },
    { speaker: "narrator_question", text: "Question 5: True or False — Both 'Plaza' and 'resume' have the same meaning in English." },
    { speaker: "Narrator", text: "False. 'Plaza' means 'deadline' and 'resume' means 'summary'." }
    ],
    translated: [
    { speaker: "Narrator", text: "" },
    { speaker: "Person1", text: "" },
    { speaker: "Person2", text: "" },
    { speaker: "Person1", text: "" },
    { speaker: "Narrator", text: "" },
    { speaker: "Narrator", text: "" },
    { speaker: "Person1", text: "" },
    { speaker: "Person2", text: "" },
    { speaker: "Person1", text: "" },
    { speaker: "Narrator", text: "" },
    { speaker: "Narrator", text: "" },
    { speaker: "Person1", text: "" },
    { speaker: "Person2", text: "" },
    { speaker: "Person1", text: "" },
    { speaker: "Narrator", text: "" },
    { speaker: "Narrator", text: "" },
    { speaker: "Person1", text: "" },
    { speaker: "Person2", text: "" },
    { speaker: "Person1", text: "" },
    { speaker: "Narrator", text: "" },
    { speaker: "Narrator", text: "" },
    { speaker: "Person1", text: "" },
    { speaker: "Person2", text: "" },
    { speaker: "Person1", text: "" },
    { speaker: "Narrator", text: "" },
    { speaker: "narrator_question", text: "" },
    { speaker: "Narrator", text: "" },
    { speaker: "narrator_question", text: "" },
    { speaker: "Narrator", text: "" },
    { speaker: "narrator_question", text: "" },
    { speaker: "Narrator", text: "" },
    { speaker: "narrator_question", text: "" },
    { speaker: "Narrator", text: "" },
    { speaker: "narrator_question", text: "" },
    { speaker: "Narrator", text: "" }
    ],
  },

  "regina-chad": {
    audioUrl: "https://res.cloudinary.com/dkhvsbyv6/video/upload/v1773400199/regina_grisolia_chad_itr3_y32be2.mp3",
    transcript: [
    { speaker: "Narrator", text: "Elara, overwhelmed by choice in a bustling department store's gift section, struggles to find a unique birthday present for her sister." },
    { speaker: "Person1", text: "These gift choices ¡me molestar! (bother me). There are too many!" },
    { speaker: "Person1", text: "I want something that ¡le encantar! (she likes a lot). Something special." },
    { speaker: "Person1", text: "All these generic presents ¡me aburrir! (bore me). This is difficult." },
    { speaker: "Narrator", text: "Elara uses `molestar`, `encantar`, and `aburrir`, which function like the verb 'gustar'. The object of the English sentence becomes the subject of the Spanish sentence, and the verb agrees with that subject." },
    { speaker: "Narrator", text: "Frustrated, Elara moves to another aisle where an item she needs seems just out of reach, but a subtle, unseen force helps her retrieve it, leaving her puzzled." },
    { speaker: "Person1", text: "I cannot ¡encontrar! (find) the right item up here." },
    { speaker: "Person1", text: "Oh! It fell right into my ¡manos! (hands). How did I ¡encontrar! (find) it?" },
    { speaker: "Narrator", text: "`Encontrar` means 'to meet or to find'. Elara wonders how the item magically appeared in her `manos`, which means 'hands'." },
    { speaker: "Narrator", text: "Sitting in the store cafe, Elara contemplates her mediocre purchase when Silas, a friendly ghost haunting the store, makes his presence known through a series of gentle, impossible phenomena." },
    { speaker: "Person1", text: "I will ¡comprar! (buy) this, even if ¡me aburrir! (it bores me)." },
    { speaker: "Person2", text: "¡Hola! (Hello). Don't let your shopping ¡molestar! (bother) you so ¡mucho! (a lot)." },
    { speaker: "Person1", text: "¡¿Quién es?! (Who is?) I heard something! And I feel ¡mucho! (a lot) confusion." },
    { speaker: "Person2", text: "I am Silas. It ¡me fascinar! (fascinates me) to help ¡personas! (people)." },
    { speaker: "Narrator", text: "`Hola` is 'Hello'. `¿Quién es?` means 'Who is?'. Silas assures Elara that helping `personas` (people) `le` `fascinar` (fascinates him). `Mucho` means 'a lot'." },
    { speaker: "Narrator", text: "Elara, surprisingly calm, accepts Silas's offer of assistance; he uses his spectral knowledge to guide her to a forgotten corner of the store containing the perfect, unexpected gift." },
    { speaker: "Person1", text: "You want to ¡mostrarme! (show me) a better gift? This is great." },
    { speaker: "Person2", text: "Yes, I can ¡explicarle! (explain to you) where the perfect gifts are hidden." },
    { speaker: "Person1", text: "Will you ¡mostrármelo! (show it to me) now? I need a good idea." },
    { speaker: "Person2", text: "Of course! Let's go ¡encontrar! (find) it." },
    { speaker: "Narrator", text: "Silas uses `mostrarme` ('to show me') and `explicarle` ('to explain to him/her'), where pronouns are attached to the infinitive. In `mostrármelo`, both indirect (`me`) and direct (`lo`) object pronouns are attached to the infinitive, with an accent added as per the rule." },
    { speaker: "Narrator", text: "With the perfect gift secured, Elara thanks Silas, who is thrilled to be acknowledged, and they part ways as unlikely friends with a promise for future shopping adventures." },
    { speaker: "Person1", text: "This is exactly what I wanted! I will ¡se la comprar! (buy it for her) for my sister." },
    { speaker: "Person2", text: "It ¡me encantar! (I loved it) to help you find it." },
    { speaker: "Person1", text: "Thank you ¡mucho! (a lot), Silas. You are a good ¡amiga! (friend)." },
    { speaker: "Person2", text: "We can ¡hablar! (talk) again soon. I am never ¡ocupada! (busy)." },
    { speaker: "Narrator", text: "`Se la comprar` demonstrates the rule 'Se for Le/Les' when a third-person indirect object pronoun (`le`) is followed by a direct object pronoun (`la`). `Mucho` means 'a lot' and `amiga` means 'friend'. `Ocupada` means 'busy'. The story concludes with Elara finding the perfect gift with Silas's help, forging an unexpected friendship." },
    { speaker: "narrator_question", text: "Question 1: True or False — The Spanish word 'política' translates to 'politics' in English." },
    { speaker: "Narrator", text: "True." },
    { speaker: "narrator_question", text: "Question 2: True or False — In Spanish, when using both a direct and an indirect object pronoun with the same verb, the direct object pronoun comes before the indirect object pronoun." },
    { speaker: "Narrator", text: "False. The indirect object pronoun comes before the direct object pronoun." },
    { speaker: "narrator_question", text: "Question 3: True or False — The verb 'molestar' means 'to like a lot' in English." },
    { speaker: "Narrator", text: "False. 'Molestar' means 'to bother'; 'encantar' means 'to like a lot'." },
    { speaker: "narrator_question", text: "Question 4: True or False — When the indirect object pronoun 'le' is used with a direct object pronoun like 'lo', the 'le' changes to 'se'." },
    { speaker: "Narrator", text: "True. This rule applies when 'le' or 'les' precedes a direct object pronoun in the third person." },
    { speaker: "narrator_question", text: "Question 5: True or False — For verbs like 'fascinar', the verb is conjugated to agree with the person experiencing the fascination." },
    { speaker: "Narrator", text: "False. The verb is modified by the object (the thing that fascinates), making the object the subject." }
    ],
    translated: [
    { speaker: "Narrator", text: "" },
    { speaker: "Person1", text: "" },
    { speaker: "Person1", text: "" },
    { speaker: "Person1", text: "" },
    { speaker: "Narrator", text: "" },
    { speaker: "Narrator", text: "" },
    { speaker: "Person1", text: "" },
    { speaker: "Person1", text: "" },
    { speaker: "Narrator", text: "" },
    { speaker: "Narrator", text: "" },
    { speaker: "Person1", text: "" },
    { speaker: "Person2", text: "" },
    { speaker: "Person1", text: "" },
    { speaker: "Person2", text: "" },
    { speaker: "Narrator", text: "" },
    { speaker: "Narrator", text: "" },
    { speaker: "Person1", text: "" },
    { speaker: "Person2", text: "" },
    { speaker: "Person1", text: "" },
    { speaker: "Person2", text: "" },
    { speaker: "Narrator", text: "" },
    { speaker: "Narrator", text: "" },
    { speaker: "Person1", text: "" },
    { speaker: "Person2", text: "" },
    { speaker: "Person1", text: "" },
    { speaker: "Person2", text: "" },
    { speaker: "Narrator", text: "" },
    { speaker: "narrator_question", text: "" },
    { speaker: "Narrator", text: "" },
    { speaker: "narrator_question", text: "" },
    { speaker: "Narrator", text: "" },
    { speaker: "narrator_question", text: "" },
    { speaker: "Narrator", text: "" },
    { speaker: "narrator_question", text: "" },
    { speaker: "Narrator", text: "" },
    { speaker: "narrator_question", text: "" },
    { speaker: "Narrator", text: "" }
    ],
  },

  "anaris-ranveer": {
    audioUrl: "https://res.cloudinary.com/dkhvsbyv6/video/upload/v1773400204/anaris_silva_ranveer_sangha_itr3_r44zq5.mp3",
    transcript: [
    { speaker: "Narrator", text: "Leo hummed, measuring flour for an ambitious lemon soufflé in her kitchen. Her Golden Retriever, Barkley, watched intently from the `la cocina` floor." },
    { speaker: "Person1", text: "Okay, Barkley, time for a soufflé! We need the best ¡la refri! (a refrigerator) has to offer." },
    { speaker: "Person2", text: "Woof! This ¡la cocina! (the kitchen) smells good. My nose is already doing a sniff test." },
    { speaker: "Person1", text: "Careful you don't knock over ¡la olla! (the cooking pot)! It's going to be hot." },
    { speaker: "Person2", text: "I'm just making sure nothing escapes ¡la estufa! (stove). It looks perfect." },
    { speaker: "Narrator", text: "`La cocina` means \"the kitchen,\" indicating where Leo is cooking. `La refri` is a casual term for \"a refrigerator.\" `La olla` refers to \"the cooking pot\" and `la estufa` is the \"stove,\" both essential kitchen items." },
    { speaker: "Narrator", text: "Leo carefully separated egg yolks, trying to achieve stiff peaks, but the whisk wasn't cooperating." },
    { speaker: "Person1", text: "This whisk is just not working, Barkley! My arm is tired." },
    { speaker: "Person2", text: "You need more enthusiasm! Maybe a ¡la licuadora! (a blender) would do a better job for those egg whites." },
    { speaker: "Person1", text: "A ¡la licuadora! (a blender) for egg whites? That's not how soufflé works! But good idea with ¡el extractor de jugos! (a juice maker) for the lemon." },
    { speaker: "Person2", text: "If you don't use ¡el extractor de jugos! (a juice maker), you'll never get to the good stuff! More power!" },
    { speaker: "Narrator", text: "Barkley suggests `la licuadora` (a blender) for whipping, and mentions `el extractor de jugos` (a juice maker), both kitchen appliances from the list." },
    { speaker: "Narrator", text: "Leo paused, realizing a critical ingredient was missing. Her eyes scanned the countertop." },
    { speaker: "Person1", text: "Oh no! No lemon zest! I forgot to buy more lemons!" },
    { speaker: "Person2", text: "No zest? This ¡la cocina! (the kitchen) disaster! Can we use peanut butter? Or perhaps some 'squirrel essence'?" },
    { speaker: "Person1", text: "No 'squirrel essence,' Barkley! We need something lemony. Maybe I have a little bit left in ¡la refri! (a refrigerator)." },
    { speaker: "Person2", text: "Check ¡la refri! (a refrigerator) quickly! The soufflé demands action. The smell inside ¡la cocina! (the kitchen) is building." },
    { speaker: "Narrator", text: "`La refri` is used again, referring to the refrigerator, where Leo hopes to find the missing ingredient. `La cocina` emphasizes the setting of their food-related predicament." },
    { speaker: "Narrator", text: "After a quick improvisation with some dried lemon peel, the soufflé batter was finally in its ramekins and ready for the heat." },
    { speaker: "Person1", text: "Into ¡el horno eléctrico! (the oven) it goes! Now we wait." },
    { speaker: "Person2", text: "Waiting is torture! What ¡está en mi sala! (is in my living room) right now? Is the timer there? Is it `in` or `out`?" },
    { speaker: "Person1", text: "The timer ¡está en mi sala! (is in my living room), yes, on the coffee table. But the soufflé is definitely `in` the oven!" },
    { speaker: "Person2", text: "Twenty-five minutes `in` the oven? My stomach says too long! Can I peek at the ¡elo! (roof or ceiling) of the soufflé? It's like watching paint dry on the ¡la pared! (the wall)." },
    { speaker: "Narrator", text: "`El horno eléctrico` refers to \"the oven.\" Leo and Barkley use `está en mi sala` which means \"is in my living room,\" showing the location of the timer. The dialogue also highlights the spatial concepts of \"in is inside\" and \"out is outside.\" `Elo` (roof or ceiling) and `la pared` (the wall) add more household descriptions." },
    { speaker: "Narrator", text: "The kitchen filled with a warm, sweet aroma as Leo carefully pulled the soufflé from the oven. It was slightly lopsided, but undeniably impressive." },
    { speaker: "Person1", text: "It's done! Our beautiful soufflé, Barkley! Now to let it cool a little." },
    { speaker: "Person2", text: "Finally! Hand me a ¡los platos! (the dishes)! This needs immediate inspection. Is it good for ¡la cama! (the bed) or ¡el garaje! (the bedroom) snack?" },
    { speaker: "Person1", text: "You're not having soufflé in ¡la cama! (the bed)! And ¡el garaje! (the bedroom) is for sleeping, not eating." },
    { speaker: "Person2", text: "Needs more bacon. Or a ¡Morino! (a sausage maker) sausage! But I will take my actual dinner now, on ¡los platos! (the dishes)." },
    { speaker: "Narrator", text: "`Los platos` means \"the dishes,\" which Barkley requests for his food. `La cama` refers to \"the bed\" and `el garaje` means \"the bedroom\" (as per the provided translation), indicating places where Barkley might want to enjoy a snack. `Morino` refers to \"a sausage maker,\" Barkley's suggestion for a different ingredient. And so, Leo's ambitious soufflé project concluded with Barkley's rather unconventional taste test and a demand for something savory." },
    { speaker: "narrator_question", text: "Question 1: True or False — The Spanish phrase `la cocina` means \"the kitchen.\"" },
    { speaker: "Narrator", text: "True. The narrator explicitly states `La cocina` means \"the kitchen.\"" },
    { speaker: "narrator_question", text: "Question 2: True or False — `La refri` is a formal term for \"a refrigerator\" in Spanish." },
    { speaker: "Narrator", text: "False. `La refri` is described as a \"casual term for 'a refrigerator'.\"" },
    { speaker: "narrator_question", text: "Question 3: True or False — According to the story, `el garaje` refers to \"the bedroom.\"" },
    { speaker: "Narrator", text: "True. The narrator states `el garaje` means \"the bedroom\" (as per the provided translation)." },
    { speaker: "narrator_question", text: "Question 4: True or False — `El horno eléctrico` refers to \"the electric blender.\"" },
    { speaker: "Narrator", text: "False. `El horno eléctrico` refers to \"the oven,\" while `la licuadora` is a blender." },
    { speaker: "narrator_question", text: "Question 5: True or False — The word `Elo` refers to a cooking pot in the story." },
    { speaker: "Narrator", text: "False. `Elo` (roof or ceiling) is mentioned, while `la olla` refers to a cooking pot." }
    ],
    translated: [
    { speaker: "Narrator", text: "" },
    { speaker: "Person1", text: "" },
    { speaker: "Person2", text: "" },
    { speaker: "Person1", text: "" },
    { speaker: "Person2", text: "" },
    { speaker: "Narrator", text: "" },
    { speaker: "Narrator", text: "" },
    { speaker: "Person1", text: "" },
    { speaker: "Person2", text: "" },
    { speaker: "Person1", text: "" },
    { speaker: "Person2", text: "" },
    { speaker: "Narrator", text: "" },
    { speaker: "Narrator", text: "" },
    { speaker: "Person1", text: "" },
    { speaker: "Person2", text: "" },
    { speaker: "Person1", text: "" },
    { speaker: "Person2", text: "" },
    { speaker: "Narrator", text: "" },
    { speaker: "Narrator", text: "" },
    { speaker: "Person1", text: "" },
    { speaker: "Person2", text: "" },
    { speaker: "Person1", text: "" },
    { speaker: "Person2", text: "" },
    { speaker: "Narrator", text: "" },
    { speaker: "Narrator", text: "" },
    { speaker: "Person1", text: "" },
    { speaker: "Person2", text: "" },
    { speaker: "Person1", text: "" },
    { speaker: "Person2", text: "" },
    { speaker: "Narrator", text: "" },
    { speaker: "narrator_question", text: "" },
    { speaker: "Narrator", text: "" },
    { speaker: "narrator_question", text: "" },
    { speaker: "Narrator", text: "" },
    { speaker: "narrator_question", text: "" },
    { speaker: "Narrator", text: "" },
    { speaker: "narrator_question", text: "" },
    { speaker: "Narrator", text: "" },
    { speaker: "narrator_question", text: "" },
    { speaker: "Narrator", text: "" }
    ],
  },
};

export default data;
